### ISSUE TITLE
Замечания по программе dec2bin

### ISSUE THREAD

**Issue by pechischev** [irina-yambatrova/OOP#2]

**Comment by pechischev** [comment]
Описание функции **atoi** говорит о неопределённом поведении при переполнении, лучше использовать **ostringstream**

**Comment by Vladi1996mir** [comment]
когда число будет равно 0 программа ничего не выведет
также нет проверок данного случая

**Comment by Vladi1996mir** [comment]
нужно проверить на максимально-допустимом числе: 4294967295
